### ISSUE TITLE
Create the menu bar in the website where all the different item categories will be displayed. 

### ISSUE THREAD

**Issue by bhargavbvs** [bhargavbvs/PrepBoost#27]
The menu bar will contain all the different categories in which the questions will be displayed to the users. For example, year wise questions, topic wise questions, bookmarks, search and more.

**Comment by srisai1234** [comment]
Added components to the menu bar such as year wise questions and topic wise questions.and as we press on topic wise button we will be seeing components according to topics.
![Image](https://user-images.githubusercontent.com/58160789/152449733-2bcc09d8-4610-4b71-bf86-1d65b8910ac3.png)
